### ISSUE TITLE
Rename maps

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/Maps#319]
**Map rename requests:**
Reason | Original Name -> Requested Name(s)
#313 | "Brisked KOTH" - - - -> "Brisked" *
#312 | "destiny" - - - - - - - -> "Destiny"
#308 | "Formogar_1" - - - - -> "Formogar" *
#310 | "ThriveV2" - - - - - - -> "Thrive_V2"
#315 | "WarlockTM" - - - -  -> "Warlock_TM" *OR* "Warlock_Tournament" *
#311 | "Windworks_DTW" --> "Windworks" *

*map.json will need updating if the file name is changed.

#309 | Maps/DTW/SunTest -> Maps/DTM/SunTest
(You break gold blocks instead of wool in this map, so it should be in DTM)

**Comment by Owehttamy** [comment]
Also, #309 wasn't opened even though technically it doesn't relate to this but here it is if truly necessary.

**Comment by BennyDoesTheStuff** [comment]
WarlockTM - Sure
Destiny - Sure
SunTest - Sure
ThriveV2 - I would probably say to instead rename the map to "Thrive 2" in both the folder as well as in the JSON file.

Formorgar and Windworks - I would probably say no, because that's the original name of the map so I don't feel we should touch this, especially considering that they're from the resourcepile.
